pub mod api;
pub mod browser;
pub mod auth;
pub mod bridge;
pub mod bridge_db;
pub mod config;
pub mod error;
pub mod files;
pub mod fs;
pub mod gateway;
pub mod log_capture;
pub mod process;
pub mod proxy;
pub mod server;
pub mod state;
pub mod sync;
pub mod ui;

#[cfg(target_os = "windows")]
pub mod service_windows;
#[cfg(target_os = "windows")]
pub mod tray;
#[cfg(target_os = "linux")]
pub mod service_linux;
